[package]
name = "spl-token-metadata-example"
version = "0.3.0"
description = "Solana Program Library Token Metadata Example Program"
documentation = "https://docs.rs/spl-token-metadata-example"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = { git = "https://github.com/jupnet/jupnet-sdk" }
spl-token-2022 = { git = "https://github.com/jupnet/token-2022", branch = "jupnet", features = ["no-entrypoint"] }
spl-token-metadata-interface = { path = "../interface" }
spl-type-length-value = { git = "https://github.com/jupnet/libraries", branch = "jupnet" }
spl-pod = { git = "https://github.com/jupnet/libraries", branch = "jupnet" }

[dev-dependencies]
solana-program-test = { git = "https://github.com/jupnet/jupnet-svm", branch = "v3.1.2" }
solana-sdk = { git = "https://github.com/jupnet/jupnet-sdk" }
solana-system-interface = { git = "https://github.com/jupnet/jupnet-sdk" }
spl-token-client = { git = "https://github.com/jupnet/token", branch = "jupnet" }
test-case = "3.3"

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[patch.crates-io]
jupnet-signature = { git = "https://github.com/jupnet/jupnet-sdk" } 
